[build]
builder = "NIXPACKS"
buildCommand = "VITE_API_URL= npm run build"

[deploy]
startCommand = "node api/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
interval = 30
timeout = 10
